sonar.projectKey=MERN-Notes-App
sonar.projectName=MERN Notes App
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.tests=backend/test,frontend/src/test

sonar.test.inclusions=backend/test/**/*.test.js,frontend/src/test/**/*.test.js,frontend/src/test/**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,backend/test/**,frontend/src/test/**,frontend/src/assets/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8